import json
import logging
from pathlib import Path

from mcp.server.fastmcp import FastMCP

logger = logging.getLogger(__name__)

_ARCH_SECTIONS = [
    "stack", "tech stack", "technology stack",
    "data model", "schema", "database",
    "auth", "authentication", "authorization",
    "error", "error handling", "error format",
    "security", "cors", "headers",
    "adr", "architecture decision",
    "api", "conventions", "standards",
    "middleware", "infrastructure",
]


def _extract_sections(text: str) -> dict:
    """Pull labelled sections from markdown text by heading keywords."""
    sections: dict[str, list[str]] = {}
    current_key = "preamble"
    current_lines: list[str] = []

    for line in text.splitlines():
        stripped = line.lstrip("#").strip().lower()
        matched = next((k for k in _ARCH_SECTIONS if k in stripped), None)
        if line.startswith("#") and matched:
            if current_lines:
                sections[current_key] = current_lines
            current_key = stripped
            current_lines = [line]
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_key] = current_lines

    return {k: "\n".join(v).strip() for k, v in sections.items() if v}


def register_arch_ingest_tool(mcp: FastMCP) -> None:

    @mcp.tool()
    async def ingest_architecture_doc(
        doc_path: str = "",
        save_summary: bool = True,
    ) -> str:
        """
        Ingest an architecture document and extract key decisions for the EPAV workflow.

        Reads a markdown architecture doc (or scans docs/arch-docs/ if no path given),
        extracts stack decisions, data model, auth strategy, error format, security rules,
        and ADR list. Optionally writes a summary to knowledge/rules/arch-summary.md.

        Args:
            doc_path: Path to the architecture doc (.md) or a directory containing
                      arch docs. If empty, looks for docs/arch-docs/ in the project root.
            save_summary: If True, writes extracted summary to
                          knowledge/rules/arch-summary.md (creates dirs if needed).

        Returns:
            JSON with extracted architecture sections and file paths written.
        """
        try:
            # Resolve the source path
            source = Path(doc_path) if doc_path else Path("docs/arch-docs")

            if not source.exists():
                return json.dumps({
                    "error": f"Path not found: {source}. "
                             "Provide doc_path or create docs/arch-docs/ with your architecture doc."
                })

            # Collect markdown files
            if source.is_file():
                md_files = [source]
            else:
                md_files = sorted(source.rglob("*.md")) + sorted(source.rglob("*.txt"))

            if not md_files:
                return json.dumps({"error": f"No markdown files found in {source}"})

            # Extract sections from all files
            all_sections: dict[str, str] = {}
            files_read = []
            for f in md_files:
                try:
                    text = f.read_text(encoding="utf-8")
                    sections = _extract_sections(text)
                    all_sections.update(sections)
                    files_read.append(str(f))
                except Exception as e:
                    logger.warning("Could not read %s: %s", f, e)

            if not all_sections:
                return json.dumps({
                    "error": "No recognisable architecture sections found. "
                             "Check that headings use standard terms (stack, auth, data model, etc.)."
                })

            files_written = []
            if save_summary:
                summary_path = Path("knowledge/rules/arch-summary.md")
                summary_path.parent.mkdir(parents=True, exist_ok=True)
                lines = ["# Architecture Summary\n", "_Auto-generated by ingest_architecture_doc_\n"]
                for section, content in all_sections.items():
                    lines.append(f"\n## {section.title()}\n\n{content}\n")
                summary_path.write_text("\n".join(lines), encoding="utf-8")
                files_written.append(str(summary_path))

            return json.dumps({
                "files_read": files_read,
                "files_written": files_written,
                "sections_extracted": list(all_sections.keys()),
                "summary": {k: v[:300] + "…" if len(v) > 300 else v
                            for k, v in all_sections.items()},
            }, indent=2)

        except Exception as e:
            logger.exception("Unexpected error in ingest_architecture_doc")
            return json.dumps({"error": f"Unexpected error: {e}"})
