import json
import logging
from pathlib import Path

from mcp.server.fastmcp import FastMCP

logger = logging.getLogger(__name__)

_KNOWLEDGE_DIRS = [
    "knowledge/rules",
    "knowledge/patterns",
    "knowledge/prompts/dev",
    "knowledge/agents",
    "knowledge/retros",
    "knowledge/templates",
]

_AGENTS_MD_TEMPLATE = """\
# AGENTS.md

> Cross-tool project rules. Every AI assistant working on this project must read this file first.
> Generated by nexus-dev-toolkit — update as the project evolves.

## Project

**Stack:** {stack}
**Repo:** {repo}

## Coding Standards

See `knowledge/rules/coding-standards.md` for the full ruleset.

### Non-negotiable rules

{rules}

## Git Conventions

- Conventional commits: `feat:`, `fix:`, `chore:`, `docs:`, `refactor:`, `test:`
- One logical change per commit
- Branch naming: `feat/`, `fix/`, `chore/`

## Quality Gates

- All acceptance criteria from the task CSV must pass before marking done
- Run `/validate` after every `/apply`
- Contribute new patterns to `knowledge/patterns/` via PR

## E→P→A→V Cycle

Every dev task follows: `/evaluate` → `/plan` → `/apply` → `/validate`
The task CSV provides the prompt — do not write prompts from scratch.
"""

_CODING_STANDARDS_TEMPLATE = """\
# Coding Standards

_Derived from architecture document. Update via PR when conventions change._

## Stack

{stack_detail}

## Rules

{rules_detail}

## Rationale

Rules without rationale get ignored. Every rule here links to the architecture
decision that produced it. When in doubt, read the arch doc in `docs/arch-docs/`.
"""


def _load_arch_summary() -> dict:
    summary_path = Path("knowledge/rules/arch-summary.md")
    if summary_path.exists():
        return {"source": str(summary_path), "text": summary_path.read_text(encoding="utf-8")}
    return {}


def _infer_stack(arch_text: str) -> str:
    text_lower = arch_text.lower()
    parts = []
    if "next.js" in text_lower or "nextjs" in text_lower:
        parts.append("Next.js")
    if "react native" in text_lower:
        parts.append("React Native")
    if "flutter" in text_lower:
        parts.append("Flutter")
    if "trpc" in text_lower or "t3" in text_lower:
        parts.append("tRPC / T3")
    if "prisma" in text_lower:
        parts.append("Prisma")
    if "postgres" in text_lower or "postgresql" in text_lower:
        parts.append("PostgreSQL")
    if "tailwind" in text_lower:
        parts.append("Tailwind CSS")
    if "supabase" in text_lower:
        parts.append("Supabase")
    return ", ".join(parts) if parts else "(update with your stack)"


def register_project_rules_tool(mcp: FastMCP) -> None:

    @mcp.tool()
    async def generate_project_rules(
        arch_doc_path: str = "",
        project_name: str = "",
        overwrite: bool = False,
    ) -> str:
        """
        Generate AGENTS.md and knowledge/ directory structure from an architecture document.

        Args:
            arch_doc_path: Path to the architecture doc (.md). If empty, uses
                           knowledge/rules/arch-summary.md if ingest_architecture_doc
                           has already run.
            project_name:  Name used in AGENTS.md header. Defaults to current dir name.
            overwrite:     If False (default), returns error if AGENTS.md already exists.

        Returns:
            JSON with list of files created/updated.
        """
        try:
            agents_path = Path("AGENTS.md")
            if agents_path.exists() and not overwrite:
                return json.dumps({
                    "error": "AGENTS.md already exists. Pass overwrite=true to replace it.",
                    "existing_path": str(agents_path.resolve()),
                })

            arch_text = ""
            source_used = ""

            if arch_doc_path and Path(arch_doc_path).exists():
                arch_text = Path(arch_doc_path).read_text(encoding="utf-8")
                source_used = arch_doc_path
            else:
                summary = _load_arch_summary()
                if summary:
                    arch_text = summary["text"]
                    source_used = summary["source"]

            if not arch_text:
                return json.dumps({
                    "error": "No architecture doc found. Run ingest_architecture_doc first, "
                             "or provide arch_doc_path.",
                })

            repo = project_name or Path(".").resolve().name
            stack = _infer_stack(arch_text)
            rules = (
                "- Follow the conventions in the architecture document\n"
                "- No console.log in production code — use the project logger\n"
                "- All secrets via environment variables — never hardcoded\n"
                "- Pin exact dependency versions (no ^ or ~)\n"
                "- Every task must pass /validate before moving on"
            )

            dirs_created = []
            for d in _KNOWLEDGE_DIRS:
                p = Path(d)
                if not p.exists():
                    p.mkdir(parents=True, exist_ok=True)
                    dirs_created.append(d)

            files_written = []

            agents_path.write_text(
                _AGENTS_MD_TEMPLATE.format(stack=stack, repo=repo, rules=rules),
                encoding="utf-8",
            )
            files_written.append(str(agents_path))

            standards_path = Path("knowledge/rules/coding-standards.md")
            standards_path.write_text(
                _CODING_STANDARDS_TEMPLATE.format(
                    stack_detail=f"**{stack}** — see arch doc for full decisions.",
                    rules_detail=rules,
                ),
                encoding="utf-8",
            )
            files_written.append(str(standards_path))

            pattern_path = Path("knowledge/patterns/implement-and-test.md")
            if not pattern_path.exists():
                pattern_path.write_text(
                    "# Implement and Test Pattern\n\n"
                    "Every dev task follows the E→P→A→V cycle:\n\n"
                    "1. `/evaluate <task>` — orient, load context, graphify blast radius\n"
                    "2. `/plan` — blueprint, wait for approval\n"
                    "3. `/apply` — implement, graphify auto-updates\n"
                    "4. `/validate` — acceptance criteria, classify issues, contribute patterns\n",
                    encoding="utf-8",
                )
                files_written.append(str(pattern_path))

            return json.dumps({
                "source_used": source_used,
                "stack_detected": stack,
                "dirs_created": dirs_created,
                "files_written": files_written,
            }, indent=2)

        except Exception as e:
            logger.exception("Unexpected error in generate_project_rules")
            return json.dumps({"error": f"Unexpected error: {e}"})
