from pathlib import Path


def sync_copilot(project_dir: str = ".") -> list[str]:
    """Sync .nexus/ to .github/copilot-instructions.md."""
    root = Path(project_dir)
    nexus = root / ".nexus"
    github_dir = root / ".github"
    github_dir.mkdir(parents=True, exist_ok=True)

    sections = ["# Project Instructions\n\n_Generated by nexus-dev-toolkit. Do not edit manually._\n"]

    rules_dir = nexus / "rules"
    if rules_dir.exists():
        for rule in sorted(rules_dir.glob("*.md")):
            sections.append(rule.read_text(encoding="utf-8"))

    skills_dir = nexus / "skills"
    if skills_dir.exists():
        sections.append("## Available Workflows\n")
        for skill in sorted(skills_dir.glob("*.md")):
            sections.append(f"### {skill.stem}\n\n{skill.read_text(encoding='utf-8')}")

    dest = github_dir / "copilot-instructions.md"
    dest.write_text("\n\n---\n\n".join(sections), encoding="utf-8")
    return [str(dest)]
