from pathlib import Path


def sync_windsurf(project_dir: str = ".") -> list[str]:
    """Sync .nexus/ to .windsurfrules."""
    root = Path(project_dir)
    nexus = root / ".nexus"

    sections = ["# Project Rules\n\n_Generated by nexus-dev-toolkit. Do not edit manually._\n"]

    rules_dir = nexus / "rules"
    if rules_dir.exists():
        for rule in sorted(rules_dir.glob("*.md")):
            sections.append(rule.read_text(encoding="utf-8"))

    skills_dir = nexus / "skills"
    if skills_dir.exists():
        sections.append("## Workflows\n")
        for skill in sorted(skills_dir.glob("*.md")):
            sections.append(f"### {skill.stem}\n\n{skill.read_text(encoding='utf-8')}")

    dest = root / ".windsurfrules"
    dest.write_text("\n\n---\n\n".join(sections), encoding="utf-8")
    return [str(dest)]
